name: Manual Trigger Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Rest Assured BDD'
        required: true
        default: 'World'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Kolkata"
        
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Install dependencies and compile
      run: mvn clean compile

    - name: Run tests
      run: mvn test
